const users = [
	{
		id: 1,
		name: 'Patrick Jane',
		emailID: 'patrickjane@gmail.com',
		username: 'patrickjane',
		phoneNumber: '9876543210',
	},
	{
		id: 2,
		name: 'Gale Burtrum',
		emailID: 'galebertram@gmail.com',
		username: 'galebertram',
		phoneNumber: '9876543210',
	},
	{
		id: 3,
		name: 'Bob Kirkland',
		emailID: 'bobkirkland@gmail.com',
		username: 'bobkirkland',
		phoneNumber: '9876543210',
	},
	{
		id: 4,
		name: 'Thomas McAllister',
		emailID: 'tommcallister@gmail.com',
		username: 'tommcallister',
		phoneNumber: '9876543210',
	},
	{
		id: 5,
		name: 'Reede Smith',
		emailID: 'reedesmith@gmail.com',
		username: 'reedesmith',
		phoneNumber: '9876543210',
	},
	{
		id: 6,
		name: 'Ray Haffner',
		emailID: 'rayhaffner@gmail.com',
		username: 'rayhaffner',
		phoneNumber: '9876543210',
	},
	{
		id: 7,
		name: 'Brad Partridge',
		emailID: 'bradpartridge@gmail.com',
		username: 'bradpartridge',
		phoneNumber: '9876543210',
	},
	{
		id: 8,
		name: 'Patrick Jane',
		emailID: 'patrickjane@gmail.com',
		username: 'patrickjane',
		phoneNumber: '9876543210',
	},
	{
		id: 9,
		name: 'Gale Burtrum',
		emailID: 'galebertram@gmail.com',
		username: 'galebertram',
		phoneNumber: '9876543210',
	},
	{
		id: 10,
		name: 'Thomas McAllister',
		emailID: 'tommcallister@gmail.com',
		username: 'tommcallister',
		phoneNumber: '9876543210',
	},
	{
		id: 11,
		name: 'Reede Smith',
		emailID: 'reedesmith@gmail.com',
		username: 'reedesmith',
		phoneNumber: '9876543210',
	},
	{
		id: 12,
		name: 'Ray Haffner',
		emailID: 'rayhaffner@gmail.com',
		username: 'rayhaffner',
		phoneNumber: '9876543210',
	},
	{
		id: 13,
		name: 'Richard Castle',
		emailID: 'rickcastle@gmail.com',
		username: 'rickcastle',
		phoneNumber: 9876543210,
	},
	{
		id: 14,
		name: 'Katherine Beckett',
		emailID: 'katherinebeckett@gmail.com',
		username: 'katherinebeckett',
		phoneNumber: 9876543210,
	},
	{
		id: 15,
		name: 'Kevin Ryan',
		emailID: 'kevinryan@gmail.com',
		username: 'kevinryan',
		phoneNumber: 9876543210,
	},
	{
		id: 16,
		name: 'Javier Esposito',
		emailID: 'javieresposito@gmail.com',
		username: 'javieresposito',
		phoneNumber: 9876543210,
	},
	{
		id: 17,
		name: 'Martha Rogers',
		emailID: 'martharogers@gmail.com',
		username: 'martharogers',
		phoneNumber: 9876543210,
	},
	{
		id: 18,
		name: 'Roy Montgomery',
		emailID: 'roymontgomery@gmail.com',
		username: 'roymontgomery',
		phoneNumber: 9876543210,
	},
	{
		id: 19,
		name: 'Richard Rogers',
		emailID: 'Richard Rogers@gmail.com',
		username: 'Richard',
		phoneNumber: 9876543210,
	},
	{
		id: 20,
		name: 'William Bracken',
		emailID: 'williambracken@gmail.com',
		username: 'williambracken',
		phoneNumber: 9876543210,
	},
];

export default users;
